import type { Metadata } from "next";
import { DM_Sans as Font } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const font = Font({
  subsets: ['latin'],
  weight: [ '300', '400', '500', '600', '700', '800', '900', '1000' ]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mode="dar">
      <body
        className={`${font.className} antialiased dark:bg-secondary-1000`}
      >
        {children}
      </body>
    </html>
  );
}
